services:
  invoicer_base: &invoicer_base
    image: alaksion/invoicer-api:0.0.14
    environment:
      INVOICER_DB_USERNAME: $INVOICER_DB_USERNAME
      INVOICER_DB_PASSWORD: $INVOICER_DB_PASSWORD
      INVOICER_DB_NAME: $INVOICER_DB_NAME
      INVOICER_DB_URL: $INVOICER_DB_URL
      INVOICER_JWT_AUDIENCE: $INVOICER_JWT_AUDIENCE
      INVOICER_JWT_ISSUER: $INVOICER_JWT_ISSUER
      INVOICER_JWT_SECRET: $INVOICER_JWT_SECRET
      INVOICER_JWT_REALM: $INVOICER_JWT_REALM
      INVOICER_API_PORT: $INVOICER_API_PORT
      INVOICER_REDIS_PORT: $INVOICER_REDIS_PORT
      INVOICER_REDIS_HOST: $INVOICER_REDIS_HOST
      INVOICER_REDIS_TTL: $INVOICER_REDIS_TTL
      INVOICER_MIN_IO_ACCESS_KEY: $INVOICER_MIN_IO_ACCESS_KEY
      INVOICER_MIN_IO_SECRET_KEY: $INVOICER_MIN_IO_SECRET_KEY
      INVOICER_MIN_IO_BUCKET: $INVOICER_MIN_IO_BUCKET
    restart: always
    networks:
      - invoicer-network
    depends_on:
      - invoicer-database
  invoicer-main:
    <<: *invoicer_base
    container_name: invoicer-api-main
    ports:
      - "8080:8080"
  invoicer-fallback:
    <<: *invoicer_base
    ports:
      - "8081:8080"
    container_name: invoicer-api-fallback
  invoicer-database:
    container_name: postgre
    image: postgres:latest
    restart: always
    networks:
      - invoicer-network
    environment:
      POSTGRES_USER: ${INVOICER_DB_USERNAME}
      POSTGRES_PASSWORD: ${INVOICER_DB_PASSWORD}
      POSTGRES_DB: ${INVOICER_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  invoicer-prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.1.0
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - invoicer-network
    depends_on:
      - invoicer-nginx
  invoicer-grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana:11.5.0
    ports:
      - "3000:3000"
    depends_on:
      - invoicer-prometheus
    networks:
      - invoicer-network
  invoicer-nginx:
    container_name: nginx
    image: nginx:1.27-perl
    restart: always
    ports:
      - "4000:4000"
    networks:
      - invoicer-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  invoicer-redis:
    container_name: redis
    restart: always
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - invoicer-network
  invoicer-elasticsearch:
    container_name: invoicer-elasticsearch
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    profiles:
      - log
    ports:
      - "9200:9200"
    networks:
      - invoicer-network
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elastisearch_data:/usr/share/elasticsearch/data
  invoicer-logstash:
    container_name: invoicer-logstash
    restart: always
    image: docker.elastic.co/logstash/logstash:7.15.1
    ports:
      - "5001:5000"
    networks:
      - invoicer-network
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - invoicer-elasticsearch
    profiles:
      - log
  invoicer-kibana:
    container_name: invoicer-kibana
    restart: always
    image: docker.elastic.co/kibana/kibana:7.15.1
    ports:
      - "5601:5601"
    networks:
      - invoicer-network
    depends_on:
      - invoicer-elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    profiles:
      - log
  invoicer-minio:
    image: minio/minio:latest
    container_name: MinIO
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: $MINIO_USER  
      MINIO_ROOT_PASSWORD: $MINIO_PASSWORD
    volumes:
      - ./minio_data:/data
    ports:
      - "9000:9000"  
      - "9001:9001"
    networks:
      - invoicer-network
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093" # caso precise de mais listeners
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
    volumes:
      - ./kraft-logs:/tmp/kraft-combined-logs
    networks:
      - invoicer-network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8100:8100"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kraft
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_KRAFT: "true"
    depends_on:
      - kafka
    networks:
      - invoicer-network
volumes:
  postgres-data:
  redis_data:
  elastisearch_data:
  minio_data:
  krfat-logs:
networks:
  invoicer-network:
    driver: bridge