apiVersion: 1

datasources:
- name: Loki
  type: loki
  access: proxy
  url: http://invoicer-loki:3100
  version: 1
  editable: false
  jsonData:
    maxLines: 1000
    derivedFields:
      - datasourceUid: 'loki'
        matcherRegex: 'traceID=(\w+)'
        name: 'TraceID'
        url: '$${__value.raw}'